apiVersion: apps/v1
kind: Deployment 
metadata:
  namespace: solar-system
  name: solar-system
  labels:
    app: solar-system
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: solar-system
  strategy: {} 
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: docker pull siddharth67/solar-system:1118877216
        name: solar-system 
        imagePullPolicy: Always 
        ports:
        - containerPort: 3000