apiVersion: apps/v1
kind: Deployment 
metadata:
  namespace: solar-system
  name: solar-system
  labels:
    app: solar-system
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: solar-system
  strategy: {} 
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: siddharth67/solar-system:v7
        name: solar-system 
        imagePullPolicy: Always 
        ports:
        - containerPort: 80