apiVersion: v1
kind: Service
metadata:
  namespace: solar-system
  name: solar-system-service
  labels:
    app: solar-system
spec:
  selector:
    app: solar-system
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: NodePort

